### ISSUE TITLE
Can you help us set up a mirror for our sub 

### ISSUE THREAD

**Issue by jasonmuldoon** [kyleratti/a-centralized-mirror#12]
- Reddit Username user/meta_uprising
- Subreddits you moderate: r/bestofworldstar/

**Comment by kyleratti** [comment]
Hi Jason,

Thanks for reaching out. Are you looking for a bot to mirror your subreddit, or are you running a bot already and want to integrate with a-mirror-bot? This project is for existing mirror bots who want to use it to post links to its mirrors on reddit, but this project doesn't actually host any mirrors itself.

**Comment by jasonmuldoon** [comment]
Hi Kyle
We need a bot to mirror any videos submitted to the site
Thanks

**Comment by kyleratti** [comment]
Jason,

My apologies, this project is just for listing out mirrors provided by others. It's best used in subs that have multiple mirror bots or one bot that offers a mirror and another that offers direct downloading.

I used to run a mirror bot, tuckbot, but have somewhat recently decided to stop running that service due to cost. It's open source if you would be interested in running it yourself:
- [tuckbot-frontend](https://github.com/kyleratti/tuckbot-frontend)
- [tuckbot-api](https://github.com/kyleratti/tuckbot-api)

It used this project (a-centralized-mirror) to share the mirror links instead of posting directly.

**Comment by AnushK-Fro** [comment]
I can potentially mirror it for you.

**Comment by jasonmuldoon** [comment]
That would be awesome. Let me know what I can do to help

**Comment by kyleratti** [comment]
@AnushK-Fro @jasonmuldoon BTW - I am happy to expand `/u/a-mirror-bot` to this subreddit for posting if you guys figure out the mirror hosting stuff! Let me know if I can help.

**Comment by jasonmuldoon** [comment]
Just let me know what I might need to do. looking forward to setting this
up

**Comment by AnushK-Fro** [comment]
Send me an email scrape@fro.email
